# ── Platform ─────────────────────────────────────────────────────────────────
# Cached once; `uname` in a hot startup path is a fork we don't need to repeat.
_os="$(uname -s)"

# ── Terminal capability ──────────────────────────────────────────────────────
# No line editor, no interactive layer. That's the case whenever TERM is
# `dumb` (zsh force-disables the `zle` option outright) or stdin isn't a
# terminal — an editor's shell mode, a `zsh -ic` from a script, a coding agent
# shelling out. In those shells the prompt and key bindings aren't just
# useless, they're noisy: starship logs `Under a 'dumb' terminal`, and fzf's
# key-binding/completion scripts fail restoring their saved options with
# `can't change option: zle` — all of it printed ahead of the output the
# caller actually wanted.
#
# Everything below still runs: PATH, mise, completions, aliases, tool hooks.
# Only the interactive layer is skipped, keyed off this flag.
if [[ "$TERM" == dumb || ! -o interactive || ! -t 0 ]]; then
  _no_zle=1
  PS1='%# '
fi

# ── Homebrew (macOS) ─────────────────────────────────────────────────────────
# Non-login shells (and Ghostty's default) don't always inherit /etc/paths.d,
# so brew-installed tools below would silently vanish. No-op if brew's already
# on PATH or isn't installed.
if [[ "$_os" == "Darwin" ]] && ! command -v brew >/dev/null 2>&1; then
  for _brew in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    if [ -x "$_brew" ]; then eval "$("$_brew" shellenv)"; break; fi
  done
  unset _brew
fi

# ── PATH ─────────────────────────────────────────────────────────────────────
# The base entries are set in zshenv, which every zsh reads — this repeats them
# because on macOS /etc/zprofile runs path_helper between zshenv and this file
# and reorders PATH so system directories come first. zshenv's `typeset -U path`
# is what keeps the repeat from duplicating: re-prepending an existing entry
# moves it back to the front instead of adding a second copy.
#
# Base entries first so ~/.zshrc.local (sourced below) can still prepend
# machine-specific paths that need to win.
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# uv / pipx drop an env script here; it extends PATH and nothing else.
[ -f "$HOME/.local/bin/env" ] && source "$HOME/.local/bin/env"

# ── Version manager (mise) ───────────────────────────────────────────────────
# Replaces asdf. One binary with no per-tool `plugin add`, and it activates by
# rewriting PATH on each prompt instead of installing shims — so a version
# change takes effect in the shell you're standing in, with no `reshim` step.
#
# Pins live in ~/.tool-versions (symlinked from this repo). mise walks parent
# directories to find config, so that file is the default for everything under
# $HOME while a project's own .tool-versions or mise.toml still wins inside it.
command -v mise >/dev/null 2>&1 && eval "$(mise activate zsh)"

# ── Completion ──────────────────────────────────────────────────────────────
# fpath additions must land before compinit, and compinit must run before
# antidote loads plugins that hook into it (fzf-tab).
#
# install.sh generates `_<cmd>` files here for tools whose completions no
# package manager provides — omp, herdr, tree-sitter — and for tools that only
# get them from Homebrew, so a Linux box ends up with the same coverage. It
# comes first on fpath deliberately: these files were generated by the exact
# binary that's installed, so they should win over a distro's stale copy.
fpath=("$HOME/.local/share/zsh/site-functions" $fpath)
[ -d "$HOME/.docker/completions" ] && fpath=("$HOME/.docker/completions" $fpath)
autoload -Uz compinit
# -C trusts the existing dump instead of scanning fpath on every shell start,
# which is the difference between a ~15ms and a ~150ms startup. The tradeoff is
# that newly added completions are invisible until the dump is rebuilt, so
# install.sh deletes ~/.zcompdump* whenever it writes new ones.
compinit -C

# ── Plugin manager (antidote, replaces Oh My Zsh) ───────────────────────────
# install.sh clones it to ~/.antidote, but a machine that got it from Homebrew
# keeps it under the brew prefix. Take whichever exists; an unguarded source
# here would throw on every single shell start.
_antidote=""
for _c in "$HOME/.antidote/antidote.zsh" \
          "${HOMEBREW_PREFIX:-/opt/homebrew}/opt/antidote/share/antidote/antidote.zsh" \
          /usr/local/opt/antidote/share/antidote/antidote.zsh \
          /usr/share/zsh-antidote/antidote.zsh; do
  [ -f "$_c" ] && { _antidote="$_c"; break; }
done
if [ -n "$_antidote" ]; then
  source "$_antidote"
  antidote load "$HOME/.zsh_plugins.txt"
else
  echo "zshrc: antidote not found — run the dotfiles install.sh to set up plugins"
fi
unset _antidote _c

# ── Carapace (multi-shell completion generator) ─────────────────────────────
# Must come after the antidote block above: carapace's completions render
# through fzf-tab (an antidote plugin), so fzf-tab has to already be loaded
# for carapace's completion output to get the fzf-tab UI instead of zsh's
# plain menu. No line editor, no point installing completion widgets —
# same reasoning as the starship/fzf guards above.
if [[ -z $_no_zle ]] && command -v carapace >/dev/null 2>&1; then
  # A bridge means: for a command carapace has no native spec for, fall back
  # to another shell's completion spec instead of giving you nothing. Order
  # is preference, first match wins.
  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
  source <(carapace _carapace)
fi
# carapace ships no spec for omp, herdr, or tree-sitter — those are exactly
# the tools install.sh hand-generates `_omp`/`_herdr`/`_tree-sitter` files
# for in the Completion section above. The two mechanisms cover disjoint
# sets of commands; don't delete the generator step as redundant with this.

# ── Machine-local secrets/overrides — never committed ───────────────────────
# See zshrc.local.example for the template. Sourced before the tool blocks
# below so it can set inputs they read (PNPM_HOME, build flags, …).
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

# omp's own per-machine overlay is separate from the block above: install.sh
# copies omp/agent/config.local.yml.example to this path on every machine
# (never committed), so a machine can override modelRoles/retry.fallbackChains
# on top of the shared, tracked omp/agent/config.yml without editing it. Guard
# on existence rather than exporting unconditionally — PI_CONFIG_FILES
# pointing at a missing file is a hard error for omp, not a silent skip.
[ -f "$HOME/.omp/agent/config.local.yml" ] && export PI_CONFIG_FILES="$HOME/.omp/agent/config.local.yml"

# ── Editor ───────────────────────────────────────────────────────────────────
# nvim when it's installed, vim as the fallback. No $SSH_CONNECTION check: this
# file runs on whichever box the shell is on — including one you've SSH'd into —
# so probing for the binary already answers "does this machine have nvim?".
# `vim` is aliased alongside so muscle memory lands in the same editor.
if command -v nvim >/dev/null 2>&1; then
  export EDITOR='nvim'
  export VISUAL='nvim'
  alias vim='nvim'
else
  export EDITOR='vim'
  export VISUAL='vim'
fi

# ── History ──────────────────────────────────────────────────────────────────
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt EXTENDED_HISTORY       # store timestamps
setopt INC_APPEND_HISTORY     # write as commands run, not just on exit
setopt SHARE_HISTORY          # share across concurrent sessions
setopt HIST_IGNORE_ALL_DUPS   # drop older duplicates, not just adjacent ones
setopt HIST_IGNORE_SPACE      # leading space = don't record
setopt HIST_REDUCE_BLANKS     # normalize whitespace before storing
setopt HIST_VERIFY            # expand history into the buffer, don't run it blind

# ── Shell quality of life ────────────────────────────────────────────────────
setopt AUTO_CD                # typing a directory name cds into it
setopt EXTENDED_GLOB          # ~/^/# glob qualifiers

# ── Prompt / navigation ──────────────────────────────────────────────────────
# starship only draws a prompt, so it's skipped outright without a line editor;
# zoxide and direnv are guarded inside their own init output and stay useful
# (`z`, per-directory env) in a scripted shell.
[[ -z $_no_zle ]] && command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
command -v zoxide   >/dev/null 2>&1 && eval "$(zoxide init zsh)"
command -v direnv   >/dev/null 2>&1 && eval "$(direnv hook zsh)"

# ── fzf ──────────────────────────────────────────────────────────────────────
# `fzf --zsh` (0.48+) is the portable path. Older distro builds — Debian and
# Ubuntu LTS ship 0.29 — don't have it and install the scripts on disk under
# one of a few paths instead.
if [[ -z $_no_zle ]] && command -v fzf >/dev/null 2>&1; then
  if fzf --zsh >/dev/null 2>&1; then
    source <(fzf --zsh)
  else
    for _f in /usr/share/doc/fzf/examples/key-bindings.zsh /usr/share/fzf/key-bindings.zsh \
              /usr/share/doc/fzf/examples/completion.zsh   /usr/share/fzf/completion.zsh; do
      [ -f "$_f" ] && source "$_f"
    done
    unset _f
  fi
fi

# fzf's own default (a `find` walk) crawls everything including .git and
# node_modules and doesn't know about .gitignore, so on a large repo it's
# both slower and full of results you can't act on. fd respects .gitignore
# by default and is fast enough that the difference is visible. Guarded
# separately from the block above: fzf itself is still useful without fd.
if command -v fd >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND='fd --type d --hidden --exclude .git'
fi

# ── Modern ls & cat ──────────────────────────────────────────────────────────
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --icons --group-directories-first'
  alias ll='eza -l --icons --group-directories-first'
  alias tree='eza --tree --icons'
fi
# Debian/Ubuntu package bat as `batcat` (name clash with an unrelated package).
if command -v bat >/dev/null 2>&1; then
  alias cat='bat'
elif command -v batcat >/dev/null 2>&1; then
  alias cat='batcat'
fi

# ── Git ──────────────────────────────────────────────────────────────────────
command -v lazygit >/dev/null 2>&1 && alias lg='lazygit'

# ── Claude Code ──────────────────────────────────────────────────────────────
# `--dangerously-skip-permissions` is what makes the tool usable at all on a
# machine this trusted; typing it out every invocation is friction with no
# safety benefit here, so it's baked into the alias instead.
command -v claude >/dev/null 2>&1 && alias claude='claude --dangerously-skip-permissions'

# ── Dotfiles help ────────────────────────────────────────────────────────────
# `dh`, not `help`: zsh's run-help and bash's builtin help both already own
# that word, and shadowing it breaks run-help for everyone.
command -v dotfiles-help >/dev/null 2>&1 && alias dh='dotfiles-help'

# ── Node / pnpm / bun ────────────────────────────────────────────────────────
if [ -z "${PNPM_HOME:-}" ]; then
  case "$_os" in
    Darwin) PNPM_HOME="$HOME/Library/pnpm" ;;
    *)      PNPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm" ;;
  esac
fi
if [ -d "$PNPM_HOME" ]; then
  export PNPM_HOME
  case ":$PATH:" in *":$PNPM_HOME:"*) ;; *) export PATH="$PNPM_HOME:$PATH" ;; esac
else
  unset PNPM_HOME
fi

[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
if [ -d "$HOME/.bun/bin" ]; then
  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
fi

# ── Go ───────────────────────────────────────────────────────────────────────
# GOPATH default rather than `go env GOPATH` — that's a subprocess on every
# shell start for a value that's ~/go unless something already set it.
if command -v go >/dev/null 2>&1; then
  [ -n "${GOBIN:-}" ] && export PATH="$GOBIN:$PATH"
  export PATH="$PATH:${GOPATH:-$HOME/go}/bin"
fi

# ── macOS-only fixups ────────────────────────────────────────────────────────
if [[ "$_os" == "Darwin" ]]; then
  # Apple ships GNU make 3.81 (2006) as *both* `make` and `gnumake`, so the
  # obvious `alias make=gnumake` is a no-op. Homebrew's make installs as
  # `gmake` (4.x) to avoid the clash — that's the one worth reaching for.
  command -v gmake >/dev/null 2>&1 && alias make="gmake"
  alias disable-chrome-updater='sudo "/Library/Application Support/Google/GoogleUpdater/Current/GoogleUpdater.app/Contents/MacOS/GoogleUpdater" --uninstall --system'
fi

# ── Linux-only fixups ────────────────────────────────────────────────────────
if [[ "$_os" == "Linux" ]]; then
  # systemctl --user needs this set over SSH / non-login shells; harmless
  # no-op when a real login session already set it via pam_systemd.
  export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
fi

# ── atuin (shell history) — keep last, it needs to own Ctrl+R ──────────────
# The upstream installer (Linux) writes this env script; Homebrew (macOS)
# doesn't, so it must stay optional.
[ -f "$HOME/.atuin/bin/env" ] && source "$HOME/.atuin/bin/env"

# Being last in this file isn't enough to own Ctrl+R. zsh-vi-mode rebuilds the
# viins/vicmd keymaps during its own init, which runs on the first precmd —
# after every line of this file — and its insert mode re-binds ^R to zsh's
# builtin history-incremental-search-backward, silently displacing atuin's
# widget. (`bindkey -M viins "^R"` returned the builtin while `-M emacs` still
# held atuin-search.) zsh-vi-mode drains zvm_after_init_commands once its
# keymaps are final, which is the supported place to bind from; fall back to
# binding inline on a machine where the plugin didn't load.
#
# atuin binds ^R in emacs and viins but only `/` in vicmd, so without the extra
# bindkey fzf's earlier `-M vicmd '^R'` would leave normal mode on a different
# history search than insert mode.
if command -v atuin >/dev/null 2>&1; then
  _atuin_bind='eval "$(atuin init zsh)"; bindkey -M vicmd "^r" atuin-search'
  if (( ${+zvm_after_init_commands} )); then
    zvm_after_init_commands+=("$_atuin_bind")
  else
    eval "$_atuin_bind"
  fi
  unset _atuin_bind
fi

unset _os _no_zle
